"""Provision (or tear down) the rate limiter's DynamoDB table + Lambda function.

hooks.RateLimiterHook can either count tool calls in-process (the default)
or delegate to a Lambda function backed by DynamoDB, so the limit holds
across containers instead of being tracked separately per container. This
script provisions that Lambda + table, deployed independently of the
AgentCore-managed CDK app in agentcore-project/ (that app is regenerated by
`agentcore create` and isn't ours to add custom infra into - see DEPLOY.md).

Called by deploy.sh after a real `agentcore deploy`, so the agent's
execution role already exists and this can grant it permission to invoke
the Lambda. Safe to re-run: creates whatever's missing, updates the
Lambda's code/config if it already exists.

    python scripts/deploy_rate_limiter.py                          # create/update
    python scripts/deploy_rate_limiter.py --project-dir <path>      # non-default scaffold location
    python scripts/deploy_rate_limiter.py --teardown                # remove everything

Requires the `boto3` dependency from requirements-deploy.txt and AWS
credentials with dynamodb:*, lambda:*, and iam:{Get,Create,Delete}Role /
{Put,Delete,Attach,Detach}RolePolicy access. Reads $AWS_REGION (defaults to
us-east-1), same convention as scripts/invoke_runtime.py.
"""

import argparse
import io
import json
import os
import shutil
import subprocess
import sys
import time
import zipfile
from pathlib import Path

import boto3
from botocore.exceptions import ClientError

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
from hooks import RATE_LIMITER_LAMBDA_NAME  # noqa: E402 (needs REPO_ROOT on sys.path first)

HANDLER_PATH = REPO_ROOT / "lambdas" / "rate_limiter" / "handler.py"
DEFAULT_PROJECT_DIR = REPO_ROOT / "agentcore-project" / "MoversHelperAgent"

TABLE_NAME = "MoversHelperAgentRateLimits"
LAMBDA_ROLE_NAME = "MoversHelperAgentRateLimiterRole"
LAMBDA_ROLE_POLICY_NAME = "UpdateRateLimitCounters"
AGENT_POLICY_NAME = "MoversHelperAgentInvokeRateLimiter"
MANAGED_LAMBDA_BASIC_EXECUTION_POLICY = (
    "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
)

REGION = os.environ.get("AWS_REGION", "us-east-1")

LAMBDA_TRUST_POLICY = json.dumps({
    "Version": "2012-10-17",
    "Statement": [{
        "Effect": "Allow",
        "Principal": {"Service": "lambda.amazonaws.com"},
        "Action": "sts:AssumeRole",
    }],
})


def _is_error(e: ClientError, code: str) -> bool:
    return e.response["Error"]["Code"] == code


def ensure_table(dynamodb) -> str:
    try:
        table = dynamodb.describe_table(TableName=TABLE_NAME)["Table"]
        print(f"== DynamoDB table '{TABLE_NAME}' already exists, skipping create ==")
        return table["TableArn"]
    except ClientError as e:
        if not _is_error(e, "ResourceNotFoundException"):
            raise

    print(f"== Creating DynamoDB table '{TABLE_NAME}' ==")
    dynamodb.create_table(
        TableName=TABLE_NAME,
        AttributeDefinitions=[{"AttributeName": "counter_id", "AttributeType": "S"}],
        KeySchema=[{"AttributeName": "counter_id", "KeyType": "HASH"}],
        BillingMode="PAY_PER_REQUEST",
    )
    dynamodb.get_waiter("table_exists").wait(TableName=TABLE_NAME)
    dynamodb.update_time_to_live(
        TableName=TABLE_NAME,
        TimeToLiveSpecification={"Enabled": True, "AttributeName": "expires_at"},
    )
    return dynamodb.describe_table(TableName=TABLE_NAME)["Table"]["TableArn"]


def ensure_lambda_role(iam, table_arn: str) -> str:
    try:
        role_arn = iam.get_role(RoleName=LAMBDA_ROLE_NAME)["Role"]["Arn"]
        print(f"== IAM role '{LAMBDA_ROLE_NAME}' already exists, skipping create ==")
    except ClientError as e:
        if not _is_error(e, "NoSuchEntity"):
            raise
        print(f"== Creating IAM role '{LAMBDA_ROLE_NAME}' ==")
        role_arn = iam.create_role(
            RoleName=LAMBDA_ROLE_NAME, AssumeRolePolicyDocument=LAMBDA_TRUST_POLICY
        )["Role"]["Arn"]
        iam.attach_role_policy(
            RoleName=LAMBDA_ROLE_NAME, PolicyArn=MANAGED_LAMBDA_BASIC_EXECUTION_POLICY
        )

    iam.put_role_policy(
        RoleName=LAMBDA_ROLE_NAME,
        PolicyName=LAMBDA_ROLE_POLICY_NAME,
        PolicyDocument=json.dumps({
            "Version": "2012-10-17",
            "Statement": [{
                "Effect": "Allow",
                "Action": "dynamodb:UpdateItem",
                "Resource": table_arn,
            }],
        }),
    )
    return role_arn


def build_zip() -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.write(HANDLER_PATH, arcname="handler.py")
    return buf.getvalue()


def ensure_lambda_function(lambda_client, role_arn: str) -> str:
    zip_bytes = build_zip()
    try:
        lambda_client.get_function(FunctionName=RATE_LIMITER_LAMBDA_NAME)
        exists = True
    except ClientError as e:
        if not _is_error(e, "ResourceNotFoundException"):
            raise
        exists = False

    if exists:
        print(f"== Updating Lambda function '{RATE_LIMITER_LAMBDA_NAME}' code ==")
        lambda_client.update_function_code(
            FunctionName=RATE_LIMITER_LAMBDA_NAME, ZipFile=zip_bytes
        )
        lambda_client.get_waiter("function_updated").wait(FunctionName=RATE_LIMITER_LAMBDA_NAME)
        lambda_client.update_function_configuration(
            FunctionName=RATE_LIMITER_LAMBDA_NAME,
            Environment={"Variables": {"RATE_LIMIT_TABLE_NAME": TABLE_NAME}},
        )
    else:
        print(f"== Creating Lambda function '{RATE_LIMITER_LAMBDA_NAME}' ==")
        # A just-created IAM role can take a few seconds to propagate before
        # Lambda will accept it - retry instead of failing on the first race.
        last_error = None
        for _ in range(6):
            try:
                lambda_client.create_function(
                    FunctionName=RATE_LIMITER_LAMBDA_NAME,
                    Runtime="python3.13",
                    Role=role_arn,
                    Handler="handler.handler",
                    Code={"ZipFile": zip_bytes},
                    Timeout=5,
                    MemorySize=128,
                    Environment={"Variables": {"RATE_LIMIT_TABLE_NAME": TABLE_NAME}},
                )
                last_error = None
                break
            except ClientError as e:
                if not _is_error(e, "InvalidParameterValueException"):
                    raise
                last_error = e
                time.sleep(5)
        if last_error:
            raise last_error

    lambda_client.get_waiter("function_active_v2").wait(FunctionName=RATE_LIMITER_LAMBDA_NAME)
    return lambda_client.get_function(FunctionName=RATE_LIMITER_LAMBDA_NAME)["Configuration"]["FunctionArn"]


def find_agent_execution_role_arn(project_dir: Path) -> str | None:
    """Best-effort: ask `agentcore status --json` for the deployed runtime's
    execution role ARN.

    AgentCore's JSON shape for this isn't a documented, stable contract this
    script can rely on, so rather than trust one specific key path, this
    scans the whole response for anything that looks like an IAM role ARN
    and returns it only if exactly one distinct candidate turns up. Callers
    treat None as "couldn't tell" and fall back to printing a manual
    aws iam put-role-policy command instead of guessing.
    """
    try:
        # Resolve to the actual executable rather than passing "agentcore"
        # straight to subprocess: on Windows an npm-installed CLI is a .CMD
        # shim, which subprocess can't launch directly without a shell
        # (shell=True would work on Windows but breaks the list-of-args
        # form on POSIX, so resolve the real path instead).
        agentcore_bin = shutil.which("agentcore") or "agentcore"
        result = subprocess.run(
            [agentcore_bin, "status", "--json"],
            cwd=project_dir, capture_output=True, text=True, timeout=30, check=True,
        )
        data = json.loads(result.stdout)
    except Exception as e:
        print(f"== Could not run `agentcore status --json` to find the execution role: {e} ==")
        return None

    found = set()

    def scan(value):
        if isinstance(value, str) and value.startswith("arn:aws:iam::") and ":role/" in value:
            found.add(value)
        elif isinstance(value, dict):
            for v in value.values():
                scan(v)
        elif isinstance(value, list):
            for v in value:
                scan(v)

    scan(data)
    if len(found) == 1:
        return found.pop()
    if not found:
        print("== No IAM role ARN found in `agentcore status --json` output ==")
    else:
        print(f"== Found multiple candidate IAM role ARNs, can't tell which is the agent's: {sorted(found)} ==")
    return None


def manual_grant_instructions(lambda_arn: str) -> str:
    policy_document = json.dumps({
        "Version": "2012-10-17",
        "Statement": [{
            "Effect": "Allow",
            "Action": "lambda:InvokeFunction",
            "Resource": lambda_arn,
        }],
    })
    return (
        "Could not auto-grant the agent's execution role permission to invoke "
        f"'{RATE_LIMITER_LAMBDA_NAME}'. Find its execution role name (agentcore status, "
        "or the IAM console - look for the role attached to the AgentCore Runtime "
        "resource) and run:\n\n"
        f"  aws iam put-role-policy --role-name <execution-role-name> "
        f"--policy-name {AGENT_POLICY_NAME} --policy-document '{policy_document}'\n\n"
        "Until that's granted, RateLimiterHook will fail open (allow every tool "
        "call) rather than block on the missing permission - see hooks.py."
    )


def grant_agent_invoke_permission(iam, lambda_arn: str, project_dir: Path) -> bool:
    role_arn = find_agent_execution_role_arn(project_dir)
    if not role_arn:
        print(manual_grant_instructions(lambda_arn))
        return False

    role_name = role_arn.rsplit("/", 1)[-1]
    print(f"== Granting execution role '{role_name}' permission to invoke the rate limiter ==")
    iam.put_role_policy(
        RoleName=role_name,
        PolicyName=AGENT_POLICY_NAME,
        PolicyDocument=json.dumps({
            "Version": "2012-10-17",
            "Statement": [{
                "Effect": "Allow",
                "Action": "lambda:InvokeFunction",
                "Resource": lambda_arn,
            }],
        }),
    )
    return True


def deploy(project_dir: Path):
    dynamodb = boto3.client("dynamodb", region_name=REGION)
    iam = boto3.client("iam", region_name=REGION)
    lambda_client = boto3.client("lambda", region_name=REGION)

    table_arn = ensure_table(dynamodb)
    role_arn = ensure_lambda_role(iam, table_arn)
    lambda_arn = ensure_lambda_function(lambda_client, role_arn)
    print(f"== Rate limiter Lambda ready: {lambda_arn} ==")

    grant_agent_invoke_permission(iam, lambda_arn, project_dir)


def teardown(project_dir: Path):
    dynamodb = boto3.client("dynamodb", region_name=REGION)
    iam = boto3.client("iam", region_name=REGION)
    lambda_client = boto3.client("lambda", region_name=REGION)

    try:
        lambda_arn = lambda_client.get_function(
            FunctionName=RATE_LIMITER_LAMBDA_NAME
        )["Configuration"]["FunctionArn"]
    except ClientError as e:
        if not _is_error(e, "ResourceNotFoundException"):
            raise
        lambda_arn = None

    if lambda_arn:
        role_arn = find_agent_execution_role_arn(project_dir)
        if role_arn:
            role_name = role_arn.rsplit("/", 1)[-1]
            try:
                iam.delete_role_policy(RoleName=role_name, PolicyName=AGENT_POLICY_NAME)
                print(f"== Removed invoke permission from '{role_name}' ==")
            except ClientError as e:
                if not _is_error(e, "NoSuchEntity"):
                    raise
        print(f"== Deleting Lambda function '{RATE_LIMITER_LAMBDA_NAME}' ==")
        lambda_client.delete_function(FunctionName=RATE_LIMITER_LAMBDA_NAME)

    try:
        iam.delete_role_policy(RoleName=LAMBDA_ROLE_NAME, PolicyName=LAMBDA_ROLE_POLICY_NAME)
    except ClientError as e:
        if not _is_error(e, "NoSuchEntity"):
            raise
    try:
        iam.detach_role_policy(
            RoleName=LAMBDA_ROLE_NAME, PolicyArn=MANAGED_LAMBDA_BASIC_EXECUTION_POLICY
        )
        iam.delete_role(RoleName=LAMBDA_ROLE_NAME)
        print(f"== Deleted IAM role '{LAMBDA_ROLE_NAME}' ==")
    except ClientError as e:
        if not _is_error(e, "NoSuchEntity"):
            raise

    try:
        dynamodb.delete_table(TableName=TABLE_NAME)
        print(f"== Deleting DynamoDB table '{TABLE_NAME}' ==")
    except ClientError as e:
        if not _is_error(e, "ResourceNotFoundException"):
            raise


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--project-dir", type=Path, default=DEFAULT_PROJECT_DIR,
        help="The agentcore-scaffolded project dir (for `agentcore status`); default matches deploy.sh's PROJECT_DIR.",
    )
    parser.add_argument("--teardown", action="store_true", help="Remove the Lambda, table, and IAM policies.")
    args = parser.parse_args()

    if args.teardown:
        teardown(args.project_dir)
    else:
        deploy(args.project_dir)


if __name__ == "__main__":
    main()
